<a href="https://colab.research.google.com/github/kj-95/google-colab/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
#iteger array;
np.array([1,2,3,4,5])


array([1, 2, 3, 4, 5])

In [5]:
np.array([1,2,3,4,5] , dtype ='float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [6]:
#nested list results in multi-dimenisional arrays
np.array([range(i,i+3) for i  in [2,4,6,]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [8]:
#create a length -10 integer array  filled with zeroes
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
#create a 3*5 floating point array filled with ones
np.ones((3,5) , dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
#create a 3*5 array filled with 3.14
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [12]:
#create a 3*3 array of  random integers in  interval[0,10]
np.random.randint(0,10,(3,3))

array([[9, 0, 6],
       [7, 6, 2],
       [0, 7, 1]])

In [13]:
#create a 3*3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])