<a href="https://colab.research.google.com/github/kj-95/google-colab/blob/main/sorting_numpy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
a = np.array([10,50,30,40])
print(np.sort(a))

[10 30 40 50]


In [5]:
def sorting(x):
  for i in range(len(x)):
    swap = i + np.argmin(x[i:1])
    (x[i], x[swap]) = (x[swap], x[i])
    return x
print(sorting(a))

[10 50 30 40]


In [6]:
import numpy as np
a = np.array([10,50,40,30,])
print(np.sort(a))

[10 30 40 50]


In [8]:
def sorting(x):
  for i in range(len(x)):
    swap = i + np.argmin(x[i:1])
    (x[i], x[swap]) = (x[swap] , x[i])
    return x
  print(sorting(a))